export const ACTION_TYPE = {
  ADD_PRODUCTS: 'ADD_PRODUCTS',
  PRODUCT_DATA_STATUS: 'PRODUCT_DATA_STATUS',
  FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
  PRODUCTS_SELECTED: 'PRODUCTS_SELECTED',
  SINGLE_PRODUCT_SELECT: 'SINGLE_PRODUCT_SELECT',
};
